version: '3.8'

services:
  main-service:
    build:
      context: ./main-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: main-service
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/ewm;AUTO_SERVER=TRUE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_SHOW_SQL: true
    volumes:
      - h2-data:/data

  stats-service:
    build:
      context: ./stats-service
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: stats-service
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/ewm;AUTO_SERVER=TRUE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_JPA_SHOW_SQL: true
    volumes:
      - h2-data:/data

volumes:
  h2-data:
