CREATE TABLE IF NOT EXISTS statistic
(
    id        long generated by default as identity PRIMARY KEY,
    uri     varchar not null,
    app     varchar not null,
    ip     varchar not null,
    TIMESTAMP   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
    );